### ISSUE TITLE
Option for exchanging the visual differentiation for content / empty pages

### ISSUE THREAD

**Issue by SChangVic** [fbgallet/roam-extension-ref-count#5]
Hi guys,

First, I want to express my appreciation for this extremely helpful and making-my-life-easier extension!

I was wondering if it's possible to add another option for exchanging the visual differentiation for content / empty pages. The reason is that in my graph, I have many more content pages than empty pages and I found gray background showed on almost everywhere on the page is a little bit annoying. However, gray ground is a great solution to identify the empty page so that I can dive into it and do some summarization there. So I want to have the exchange option for the visual differentiation.

Thank you for taking this request into account.

**Comment by fbgallet** [comment]
Hi,

I will considere this option for the next update, but in the meantime, you can add this CSS block on your `[[roam/css]]` page:
```css
.rm-page-ref--link:has(+ span > sup.rc-notvoid-page),
.rm-page-ref--link:has(+ span + span > sup.rc-notvoid-page) {
  background-color: inherit;
}
.rm-page-ref--link:has(+ span > sup.rc-void-page),
.rm-page-ref--link:has(+ span + span > sup.rc-void-page) {
  background-color: rgba(128, 128, 128, 0.1);
}
```

Let me know if it's working for you.
